<?php
return [
    'ListTour.index' => ['controller' => 'ListTourController', 'action' => 'index'],
    'ListTour.details' => ['controller' => 'ListTourController', 'action' => 'details'],
    'ListTour.addToWishlist' => ['controller' => 'ListTourController', 'action' => 'addToWishlist'],
    'BookingTour.index' => ['controller' => 'BookingTourController', 'action' => 'index'],
    'BookingTour.book' => ['controller' => 'BookingTourController', 'action' => 'book'],
    'settinguser.edit' => ['controller' => 'SettingUserController', 'action' => 'edit'],
    'settinguser.update' => ['controller' => 'SettingUserController', 'action' => 'update'],
    'settinguser.changePassword' => ['controller' => 'SettingUserController', 'action' => 'changePassword'],
    'settinguser.updatePassword' => ['controller' => 'SettingUserController', 'action' => 'updatePassword'],
    'settinguser.bookingHistory' => ['controller' => 'SettingUserController', 'action' => 'bookingHistory'],
    'settinguser.updateBookingHistory' => ['controller' => 'SettingUserController', 'action' => 'updateBookingHistory'],
    'settinguser.detailBookingHistory' => ['controller' => 'SettingUserController', 'action' => 'detailBookingHistory'],
    'settinguser.favoriteTour' => ['controller' => 'SettingUserController', 'action' => 'favoriteTour'],
    'settinguser.updateFavoriteTour' => ['controller' => 'SettingUserController', 'action' => 'updateFavoriteTour'],
    'user.index' => ['controller' => 'UserController', 'action' => 'index'],
    'tour.index' => ['controller' => 'TourController', 'action' => 'index'],
    'tour.create' => ['controller' => 'TourController', 'action' => 'create'],
    'tour.update' => ['controller' => 'TourController', 'action' => 'update'],
    'tour.delete' => ['controller' => 'TourController', 'action' => 'delete'],
    'itinerary.index' => ['controller' => 'ItineraryController', 'action' => 'index'],
    'itinerary.edit' => ['controller' => 'ItineraryController', 'action' => 'edit'],
    'itinerary.getDetails' => ['controller' => 'ItineraryController', 'action' => 'getDetails'],
    'itinerary.save' => ['controller' => 'ItineraryController', 'action' => 'save'],
    'itinerary.delete' => ['controller' => 'ItineraryController', 'action' => 'delete'],
    'booking.index' => ['controller' => 'BookingController', 'action' => 'index'],
    'service.index' => ['controller' => 'ServiceController', 'action' => 'index'],
];
?>