<?php
return [
    'ListTour.index' => ['controller' => 'ListTourController', 'action' => 'index'],
    'ListTour.details' => ['controller' => 'ListTourController', 'action' => 'details'],
    'ListTour.addToWishlist' => ['controller' => 'ListTourController', 'action' => 'addToWishlist'],
    'BookingTour.index' => ['controller' => 'BookingTourController', 'action' => 'index'],
    'BookingTour.book' => ['controller' => 'BookingTourController', 'action' => 'book'],
    'settinguser.edit' => ['controller' => 'SettingUserController', 'action' => 'edit'],
    'settinguser.update' => ['controller' => 'SettingUserController', 'action' => 'update'],
    'settinguser.changePassword' => ['controller' => 'SettingUserController', 'action' => 'changePassword'],
    'settinguser.updatePassword' => ['controller' => 'SettingUserController', 'action' => 'updatePassword'],
    'settinguser.bookingHistory' => ['controller' => 'SettingUserController', 'action' => 'bookingHistory'],
    'settinguser.updateBookingHistory' => ['controller' => 'SettingUserController', 'action' => 'updateBookingHistory'],
    'settinguser.detailBookingHistory' => ['controller' => 'SettingUserController', 'action' => 'detailBookingHistory'],
    'settinguser.favoriteTour' => ['controller' => 'SettingUserController', 'action' => 'favoriteTour'],
    'settinguser.updateFavoriteTour' => ['controller' => 'SettingUserController', 'action' => 'updateFavoriteTour'],
    'user.index' => ['controller' => 'UserController', 'action' => 'index'],
    'Tour.index' => ['controller' => 'TourController', 'action' => 'index'],
    'Tour.create' => ['controller' => 'TourController', 'action' => 'create'],
    'Tour.update' => ['controller' => 'TourController', 'action' => 'update'],
    'Tour.delete' => ['controller' => 'TourController', 'action' => 'delete'],
    'Tour.getAddForm' => ['controller' => 'TourController', 'action' => 'getAddForm'],
    'Tour.getEditForm' => ['controller' => 'TourController', 'action' => 'getEditForm'],
    'TourItinerary.index' => ['controller' => 'TourItineraryController', 'action' => 'index'],
    'TourItinerary.getForm' => ['controller' => 'TourItineraryController', 'action' => 'getForm'],
    'TourItinerary.save' => ['controller' => 'TourItineraryController', 'action' => 'save'],
    'TourItinerary.delete' => ['controller' => 'TourItineraryController', 'action' => 'delete'],
    'BookingAdmin.index' => ['controller' => 'BookingAdminController', 'action' => 'index'],
    'BookingAdmin.detail' => ['controller' => 'BookingAdminController', 'action' => 'detail'],
    'Service.index' => ['controller' => 'ServiceController', 'action' => 'index'],
    'Service.create' => ['controller' => 'ServiceController', 'action' => 'create'],
    'Service.update' => ['controller' => 'ServiceController', 'action' => 'update'],
    'Service.delete' => ['controller' => 'ServiceController', 'action' => 'delete'],
    'Service.getAddForm' => ['controller' => 'ServiceController', 'action' => 'getAddForm'],
    'Service.getEditForm' => ['controller' => 'ServiceController', 'action' => 'getEditForm'],
    'TourService.index' => ['controller' => 'TourServiceController', 'action' => 'index'],
    'TourService.getForm' => ['controller' => 'TourServiceController', 'action' => 'getForm'],
    'TourService.save' => ['controller' => 'TourServiceController', 'action' => 'save'],
];
?>